apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: bucket-eventing-pipe
spec:
  integration:
    dependencies:
    - "camel:cloudevents"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: aws-s3-source
    properties:
      bucketNameOrArn: example
      accessKey: ACCESSKEY
      secretKey: SECRETKEY
      region: region
    dataTypes:
      out:
        scheme: aws2-s3
        format: application-cloudevents
  sink:
    dataTypes:
      in:
        scheme: http
        format: application-cloudevents
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: http-sink
    properties:
      url: "http://bucket-eventing.bucket-eventing.svc.cluster.local:8080"
      method: POST
