apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bucket-eventing
spec:
  template:
    spec:
      containers:
      - image: quay.io/jkeam/bucket-eventing
        ports:
        - containerPort: 8080
